language: node_js
node_js:
  - '8.9.3'
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run test:unit
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
